In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [39]:
data = load_iris()
X = iris.data    #training data
y = iris.target
print("feature name",iris.feature_names)
print("target name",iris.target_names)



feature name ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target name ['setosa' 'versicolor' 'virginica']


In [40]:
len(X)

150

In [41]:
Q=np.array([4.3,3.7,1.1,0.1])

In [42]:
X[50,:]

array([7. , 3.2, 4.7, 1.4])

In [43]:
X[:,3]

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [44]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [45]:
M = 150   
N = 4     

Distance = []

for ob in range(M):
    Sum = 0
    for f in range(N):
        Sum = Sum + abs(X[ob, f] - Q[f])
     #X[ob,f]-Q[1,f]   #np.abs is manhattan distance
    Distance.append(Sum / N)

print(Distance)

[0.35, 0.42500000000000016, 0.3000000000000001, 0.35, 0.30000000000000004, 0.55, 0.27499999999999997, 0.3750000000000001, 0.3250000000000002, 0.40000000000000013, 0.40000000000000013, 0.3500000000000001, 0.375, 0.17500000000000004, 0.49999999999999994, 0.7000000000000002, 0.45000000000000007, 0.37499999999999994, 0.575, 0.37499999999999983, 0.5250000000000002, 0.37499999999999994, 0.15, 0.55, 0.42500000000000004, 0.5000000000000001, 0.4500000000000001, 0.40000000000000013, 0.40000000000000013, 0.3750000000000001, 0.42500000000000004, 0.5250000000000001, 0.42499999999999993, 0.525, 0.42500000000000016, 0.35000000000000003, 0.4250000000000001, 0.2500000000000001, 0.2750000000000002, 0.4, 0.32500000000000007, 0.5000000000000001, 0.22500000000000012, 0.4750000000000001, 0.49999999999999983, 0.425, 0.3749999999999999, 0.29999999999999993, 0.375, 0.3750000000000001, 2.0250000000000004, 1.85, 2.1, 1.675, 2.0, 1.7250000000000003, 1.875, 1.2500000000000002, 1.95, 1.5, 1.4250000000000003, 1.7000

In [46]:
len(Distance)

150

In [47]:
import scipy
from scipy import stats

Kclass = np.array([1,1,1,0,0])
final_class = stats.mode(Kclass)
print('k_nearest_class',Kclass)
print('final_class',final_class)


k_nearest_class [1 1 1 0 0]
final_class ModeResult(mode=1, count=3)


In [48]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [51]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

knn = KNeighborsClassifier(n_neighbors=3)   
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report\n", classification_report(y_test, y_pred))


Accuracy: 1.0

Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [53]:
Distance

[0.35,
 0.42500000000000016,
 0.3000000000000001,
 0.35,
 0.30000000000000004,
 0.55,
 0.27499999999999997,
 0.3750000000000001,
 0.3250000000000002,
 0.40000000000000013,
 0.40000000000000013,
 0.3500000000000001,
 0.375,
 0.17500000000000004,
 0.49999999999999994,
 0.7000000000000002,
 0.45000000000000007,
 0.37499999999999994,
 0.575,
 0.37499999999999983,
 0.5250000000000002,
 0.37499999999999994,
 0.15,
 0.55,
 0.42500000000000004,
 0.5000000000000001,
 0.4500000000000001,
 0.40000000000000013,
 0.40000000000000013,
 0.3750000000000001,
 0.42500000000000004,
 0.5250000000000001,
 0.42499999999999993,
 0.525,
 0.42500000000000016,
 0.35000000000000003,
 0.4250000000000001,
 0.2500000000000001,
 0.2750000000000002,
 0.4,
 0.32500000000000007,
 0.5000000000000001,
 0.22500000000000012,
 0.4750000000000001,
 0.49999999999999983,
 0.425,
 0.3749999999999999,
 0.29999999999999993,
 0.375,
 0.3750000000000001,
 2.0250000000000004,
 1.85,
 2.1,
 1.675,
 2.0,
 1.7250000000000003,
 1.875,
 

In [52]:
np.sort(Distance)

array([0.15 , 0.175, 0.225, 0.25 , 0.275, 0.275, 0.3  , 0.3  , 0.3  ,
       0.325, 0.325, 0.35 , 0.35 , 0.35 , 0.35 , 0.375, 0.375, 0.375,
       0.375, 0.375, 0.375, 0.375, 0.375, 0.375, 0.4  , 0.4  , 0.4  ,
       0.4  , 0.4  , 0.425, 0.425, 0.425, 0.425, 0.425, 0.425, 0.425,
       0.45 , 0.45 , 0.475, 0.5  , 0.5  , 0.5  , 0.5  , 0.525, 0.525,
       0.525, 0.55 , 0.55 , 0.575, 0.7  , 1.225, 1.25 , 1.3  , 1.425,
       1.45 , 1.45 , 1.5  , 1.5  , 1.55 , 1.55 , 1.575, 1.575, 1.6  ,
       1.6  , 1.625, 1.625, 1.625, 1.65 , 1.65 , 1.65 , 1.675, 1.675,
       1.7  , 1.7  , 1.7  , 1.7  , 1.725, 1.725, 1.75 , 1.775, 1.825,
       1.825, 1.825, 1.85 , 1.85 , 1.875, 1.875, 1.875, 1.9  , 1.9  ,
       1.95 , 1.95 , 1.975, 1.975, 2.   , 2.   , 2.   , 2.   , 2.025,
       2.05 , 2.05 , 2.05 , 2.075, 2.075, 2.075, 2.1  , 2.1  , 2.1  ,
       2.1  , 2.125, 2.125, 2.15 , 2.15 , 2.175, 2.175, 2.175, 2.2  ,
       2.225, 2.225, 2.25 , 2.25 , 2.25 , 2.275, 2.275, 2.35 , 2.35 ,
       2.35 , 2.375,